server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/erpdb?currentSchema=erpdb
    username: postgres
    password: ninest

mybatis:
   mapper-locations: classpath*:/mapper/**/*.xml
   type-aliases-package: com.JDERP.ERP.model
   map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    # log4jdbc 설정
    jdbc.sqlonly: OFF         # ✅ 실행된 SQL만 표시
    jdbc.sqltiming: OFF         # ❌ 실행 시간 포함된 로그 끄기
    jdbc.audit: OFF             # ❌ Connection, ResultSet 메소드 로그 끄기
    jdbc.resultset: OFF         # ❌ ResultSet 관련 메서드 로그 끄기
    jdbc.connection: OFF        # ❌ Connection 관련 메서드 로그 끄기
    jdbc.resultsettable: OFF
